version: "3.8"
x-base-service: &bs
  pull_policy: always
  restart: on-failure:3
  logging:
    driver: "json-file"
    options:
      max-size: 10m
      max-file: 3
  networks:
    - net
  env_file:
    - .env.dev
services:
  aktools:
    <<: *bs
    image: kkqy/aktools:latest
    container_name: finai-aktools
    ports:
      - 8080:8080
  pgdb:
    <<: *bs
    image: postgres:18-alpine
    container_name: finai-pgdb
    ports:
      - 5432:5432
    volumes:
      - pgdb-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: finai
  redis:
    <<: *bs
    image: redis:8-alpine
    container_name: finai-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  pgdb-data:
  redis-data:
networks:
  net:
